version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - '8080:8080'
    volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
      - /home/jenkins/udemy-project/jenkins-data:/var/jenkins_home
    networks:
      - net
networks:
  net: